### ISSUE TITLE
Plugin is not detected as compatible with IntelliJ IDEA 2023.3.6

### ISSUE THREAD

**Issue by HeikoNitrobox** [TNG/jgiven-intellij-plugin#135]
I would like to use your plugin with 2023 Version, but IntelliJ prevents it.

Plugin Page: https://plugins.jetbrains.com/plugin/9670-jgiven
<img width="413" alt="image" src="https://github.com/TNG/jgiven-intellij-plugin/assets/99733931/b7053f33-7a2e-44e5-9cdc-2c1f2aa5f129">

In PlugIn Search of Idea is no Entry visible.

**Comment by l-1squared** [comment]
Hi, I guess that is because of https://github.com/TNG/jgiven-intellij-plugin/pull/134#pullrequestreview-1985464661 (now merged). 
Just have a tiny bit of patience.

**Comment by HeikoNitrobox** [comment]
Thanks for the fast support.
